/* Automatically generated by wasm2c */
#ifndef RECOMPILABLE_H_GENERATED_
#define RECOMPILABLE_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_a;

typedef struct w2c_xatcorewasm__full {
  struct w2c_a* w2c_a_instance;
  u32 w2c_g0;
  wasm_rt_memory_t w2c_o;
  wasm_rt_funcref_table_t w2c_q;
} w2c_xatcorewasm__full;

void wasm2c_xatcorewasm__full_instantiate(w2c_xatcorewasm__full*, struct w2c_a*);
void wasm2c_xatcorewasm__full_free(w2c_xatcorewasm__full*);
wasm_rt_func_type_t wasm2c_xatcorewasm__full_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'a' 'a' */
void w2c_a_a(struct w2c_a*, u32, u32, u32);

/* import: 'a' 'b' */
void w2c_a_b(struct w2c_a*, u32, u32, u32, u32);

/* import: 'a' 'c' */
u32 w2c_a_c(struct w2c_a*, u32, u32, u32);

/* import: 'a' 'd' */
void w2c_a_d(struct w2c_a*);

/* import: 'a' 'e' */
u32 w2c_a_e(struct w2c_a*, u32, u32, u32, u32);

/* import: 'a' 'f' */
f64 w2c_a_f(struct w2c_a*);

/* import: 'a' 'g' */
u32 w2c_a_g(struct w2c_a*, u32);

/* import: 'a' 'h' */
void w2c_a_h(struct w2c_a*, u32, u32, u32);

/* import: 'a' 'i' */
void w2c_a_i(struct w2c_a*, u32);

/* import: 'a' 'j' */
u32 w2c_a_j(struct w2c_a*, u32);

/* import: 'a' 'k' */
void w2c_a_k(struct w2c_a*, u32, u32, u32);

/* import: 'a' 'l' */
u32 w2c_a_l(struct w2c_a*, u32, u32, u32, u32, u32);

/* import: 'a' 'm' */
u32 w2c_a_m(struct w2c_a*, u32, u32);

/* import: 'a' 'n' */
u32 w2c_a_n(struct w2c_a*, u32, u32);

/* export: 'o' */
wasm_rt_memory_t* w2c_xatcorewasm__full_o(w2c_xatcorewasm__full* instance);

/* export: 'p' */
void w2c_xatcorewasm__full_p(w2c_xatcorewasm__full*);

/* export: 'q' */
wasm_rt_funcref_table_t* w2c_xatcorewasm__full_q(w2c_xatcorewasm__full* instance);

/* export: 'r' */
u32 w2c_xatcorewasm__full_r(w2c_xatcorewasm__full*, u32);

/* export: 's' */
void w2c_xatcorewasm__full_s(w2c_xatcorewasm__full*, u32);

/* export: 't' */
u32 w2c_xatcorewasm__full_t(w2c_xatcorewasm__full*, u32, u32, u32);

/* export: 'u' */
u32 w2c_xatcorewasm__full_u(w2c_xatcorewasm__full*, u32);

/* export: 'v' */
u32 w2c_xatcorewasm__full_v(w2c_xatcorewasm__full*);

/* export: 'w' */
void w2c_xatcorewasm__full_w(w2c_xatcorewasm__full*, u32);

/* export: 'x' */
u32 w2c_xatcorewasm__full_x(w2c_xatcorewasm__full*, u32);

/* export: 'y' */
u32 w2c_xatcorewasm__full_y(w2c_xatcorewasm__full*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* RECOMPILABLE_H_GENERATED_ */
